apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aksbot
  name: aksbot-service
spec:
  ports:
  - port: 7114
    name: botport
    protocol: TCP
    targetPort: 7114
  - port: 7222
    name: custdata
    protocol: TCP
    targetPort: 7222
  selector:
    app: aksbot
  type: LoadBalancer
status:
  loadBalancer: {}
